// <auto-generated />
using System;
using BhDream.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BhDream.Infrastructure.Migrations
{
    [DbContext(typeof(QuantDbContext))]
    partial class QuantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnderlyingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnderlyingId", "Expiry", "StrikePrice", "OptionType")
                        .IsUnique();

                    b.ToTable("OptionContracts");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionGreeksAndIv", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RfrMarket")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RfrTenor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<double>("Gamma")
                        .HasColumnType("REAL");

                    b.Property<double>("ImpliedVolatility")
                        .HasColumnType("REAL");

                    b.Property<double>("Rho")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta")
                        .HasColumnType("REAL");

                    b.Property<double>("Vega")
                        .HasColumnType("REAL");

                    b.Property<double>("Vomma")
                        .HasColumnType("REAL");

                    b.HasKey("ContractId", "OptionHistoryId", "RfrMarket", "RfrTenor");

                    b.HasIndex("OptionHistoryId", "ContractId");

                    b.ToTable("OptionGreeksAndIvs");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChangeInUnderlyingValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Close")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Ltp")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NumberOfContracts")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PremiumTurnover")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SettlePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnderlyingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "Date")
                        .IsUnique();

                    b.ToTable("OptionHistories");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionPricingParameterSnapshot", b =>
                {
                    b.Property<decimal>("Close")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionContractId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RfrMarket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RfrTenor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RfrTenorDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RiskFreeRateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnderlyingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_OptionPricingParameterSnapshots", (string)null);
                });

            modelBuilder.Entity("BhDream.Domain.Entities.RiskFreeRate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("India");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Tenor", "Market");

                    b.HasIndex("Date", "Market");

                    b.ToTable("RiskFreeRates", (string)null);
                });

            modelBuilder.Entity("BhDream.Domain.Entities.Underlying", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Underlyings");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.Underlying", "Underlying")
                        .WithMany("Contracts")
                        .HasForeignKey("UnderlyingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Underlying");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionGreeksAndIv", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.OptionContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BhDream.Domain.Entities.OptionHistory", "OptionHistory")
                        .WithMany()
                        .HasForeignKey("OptionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("OptionHistory");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistory", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.OptionContract", "Contract")
                        .WithMany("Histories")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.Underlying", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
