// <auto-generated />
using System;
using BhDream.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BhDream.Infrastructure.Migrations
{
    [DbContext(typeof(QuantDbContext))]
    partial class QuantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BhDream.Domain.Entities.MlModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelMetrics")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ModelReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelName", "Status", "StartDateTime", "EndDateTime");

                    b.ToTable("ml_models", (string)null);
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UnderlyingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnderlyingId", "Expiry", "StrikePrice", "OptionType")
                        .IsUnique();

                    b.ToTable("OptionContracts");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionGreeksAndIv", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RfrMarket")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RfrTenor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("BenchMarkDelta")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkGamma")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkImpliedVolatility")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkRho")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkTheta")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkVega")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("BenchMarkVomma")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Delta")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Gamma")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("ImpliedVolatility")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Rho")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Theta")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Vega")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Vomma")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.HasKey("ContractId", "OptionHistoryId", "RfrMarket", "RfrTenor");

                    b.HasIndex("OptionHistoryId", "ContractId");

                    b.ToTable("OptionGreeksAndIvs");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangeInUnderlyingValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Close")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Ltp")
                        .HasColumnType("numeric");

                    b.Property<long?>("NumberOfContracts")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PremiumTurnover")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SettlePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnderlyingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "Date")
                        .IsUnique();

                    b.ToTable("OptionHistories");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistoryRfrSync", b =>
                {
                    b.Property<Guid>("OptionHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RfrTenor")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RfrMarket")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OptionHistoryId", "RfrTenor", "RfrMarket");

                    b.HasIndex("Date", "RfrTenor", "RfrMarket");

                    b.ToTable("OptionHistoryRfrSync");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionPricingParameterSnapshot", b =>
                {
                    b.Property<decimal>("Close")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Close");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Date");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Expiry");

                    b.Property<Guid>("OptionContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("optioncontractid");

                    b.Property<Guid>("OptionHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("optionhistoryid");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer")
                        .HasColumnName("OptionType");

                    b.Property<string>("RfrMarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rfrmarket");

                    b.Property<string>("RfrTenor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rfrtenor");

                    b.Property<int>("RfrTenorDays")
                        .HasColumnType("integer")
                        .HasColumnName("rfrtenordays");

                    b.Property<decimal>("RiskFreeRateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("riskfreeratevalue");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("StrikePrice");

                    b.Property<decimal>("UnderlyingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("UnderlyingValue");

                    b.ToTable((string)null);

                    b.ToView("view_optionpricingparametersnapshots", (string)null);
                });

            modelBuilder.Entity("BhDream.Domain.Entities.RiskFreeRate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tenor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Market")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("India");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Date", "Tenor", "Market");

                    b.HasIndex("Date", "Market", "Tenor");

                    b.ToTable("RiskFreeRates", (string)null);
                });

            modelBuilder.Entity("BhDream.Domain.Entities.Underlying", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Underlyings");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.Underlying", "Underlying")
                        .WithMany("Contracts")
                        .HasForeignKey("UnderlyingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Underlying");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionGreeksAndIv", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.OptionContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BhDream.Domain.Entities.OptionHistory", "OptionHistory")
                        .WithMany()
                        .HasForeignKey("OptionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("OptionHistory");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistory", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.OptionContract", "Contract")
                        .WithMany("Histories")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionHistoryRfrSync", b =>
                {
                    b.HasOne("BhDream.Domain.Entities.OptionHistory", "OptionHistory")
                        .WithMany()
                        .HasForeignKey("OptionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BhDream.Domain.Entities.RiskFreeRate", "RiskFreeRate")
                        .WithMany()
                        .HasForeignKey("Date", "RfrTenor", "RfrMarket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionHistory");

                    b.Navigation("RiskFreeRate");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.OptionContract", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("BhDream.Domain.Entities.Underlying", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
