# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x08\x62h_dream\"\x80\x02\n\x1aOptionRequestSnapshotProto\x12\x19\n\x11option_history_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x02 \x01(\t\x12\x12\n\nrfr_market\x18\x03 \x01(\t\x12\x11\n\trfr_tenor\x18\x04 \x01(\t\x12\x18\n\x10underlying_value\x18\x05 \x01(\x01\x12\x14\n\x0cstrike_price\x18\x06 \x01(\x01\x12\x1a\n\x12option_price_close\x18\x07 \x01(\x01\x12\x16\n\x0erisk_free_rate\x18\x08 \x01(\x01\x12\x16\n\x0etime_to_expiry\x18\t \x01(\x01\x12\x0f\n\x07is_call\x18\n \x01(\x08\"s\n\x17OptionBatchRequestProto\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x46\n\x18option_request_snapshots\x18\x02 \x03(\x0b\x32$.bh_dream.OptionRequestSnapshotProto\"\xa5\x02\n\x1fOptionGreeksResultSnapshotProto\x12\x19\n\x11option_history_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x02 \x01(\t\x12\x12\n\nrfr_market\x18\x03 \x01(\t\x12\x11\n\trfr_tenor\x18\x04 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x01\x12\r\n\x05gamma\x18\x06 \x01(\x01\x12\x0c\n\x04vega\x18\x07 \x01(\x01\x12\r\n\x05theta\x18\x08 \x01(\x01\x12\x0b\n\x03rho\x18\t \x01(\x01\x12\r\n\x05vomma\x18\n \x01(\x01\x12\x1a\n\x12implied_volatility\x18\x0b \x01(\x01\x12\x38\n\x10\x62\x65nchmark_result\x18\x0c \x01(\x0b\x32\x1e.bh_dream.BenchmarkResultProto\"\x89\x01\n\x14\x42\x65nchmarkResultProto\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x01\x12\r\n\x05gamma\x18\x02 \x01(\x01\x12\x0c\n\x04vega\x18\x03 \x01(\x01\x12\r\n\x05theta\x18\x04 \x01(\x01\x12\x0b\n\x03rho\x18\x05 \x01(\x01\x12\r\n\x05vomma\x18\x06 \x01(\x01\x12\x1a\n\x12implied_volatility\x18\x07 \x01(\x01\"\x83\x01\n\x1cOptionGreeksBatchResultProto\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12Q\n\x1eoption_greeks_result_snapshots\x18\x02 \x03(\x0b\x32).bh_dream.OptionGreeksResultSnapshotProtoB\"\xaa\x02\x1f\x42hDream.Infrastructure.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\037BhDream.Infrastructure.Protobuf'
  _globals['_OPTIONREQUESTSNAPSHOTPROTO']._serialized_start=31
  _globals['_OPTIONREQUESTSNAPSHOTPROTO']._serialized_end=287
  _globals['_OPTIONBATCHREQUESTPROTO']._serialized_start=289
  _globals['_OPTIONBATCHREQUESTPROTO']._serialized_end=404
  _globals['_OPTIONGREEKSRESULTSNAPSHOTPROTO']._serialized_start=407
  _globals['_OPTIONGREEKSRESULTSNAPSHOTPROTO']._serialized_end=700
  _globals['_BENCHMARKRESULTPROTO']._serialized_start=703
  _globals['_BENCHMARKRESULTPROTO']._serialized_end=840
  _globals['_OPTIONGREEKSBATCHRESULTPROTO']._serialized_start=843
  _globals['_OPTIONGREEKSBATCHRESULTPROTO']._serialized_end=974
# @@protoc_insertion_point(module_scope)
